name: usq
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.10.0
  firebase_auth: ^5.4.0
  cloud_firestore: ^5.6.1
  uuid: ^4.5.1
  firebase_messaging: ^15.2.0
  http: ^1.2.2
  googleapis_auth: ^1.6.0
  flutter_dotenv: ^5.2.1
  image_picker: ^1.1.2
  path_provider: ^2.1.5
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
   - lib/src/images/