// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmnDOhaWPRZSVZ9RbQIPWphomha6XgkmI',
    appId: '1:848836773765:web:7afecd3e82f347072da6ec',
    messagingSenderId: '848836773765',
    projectId: 'usq1-7119d',
    authDomain: 'usq1-7119d.firebaseapp.com',
    storageBucket: 'usq1-7119d.firebasestorage.app',
    measurementId: 'G-M47Y121JPM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYzhSV9DxpZeWbZfsJbgTCAZRvcsXRFCA',
    appId: '1:848836773765:android:315df3e44c60d6ec2da6ec',
    messagingSenderId: '848836773765',
    projectId: 'usq1-7119d',
    storageBucket: 'usq1-7119d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuiLc_0nY2k-uXABtEyWzodQDESX5krGk',
    appId: '1:848836773765:ios:48f5c3317658319e2da6ec',
    messagingSenderId: '848836773765',
    projectId: 'usq1-7119d',
    storageBucket: 'usq1-7119d.firebasestorage.app',
    iosBundleId: 'com.example.usq',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuiLc_0nY2k-uXABtEyWzodQDESX5krGk',
    appId: '1:848836773765:ios:48f5c3317658319e2da6ec',
    messagingSenderId: '848836773765',
    projectId: 'usq1-7119d',
    storageBucket: 'usq1-7119d.firebasestorage.app',
    iosBundleId: 'com.example.usq',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmnDOhaWPRZSVZ9RbQIPWphomha6XgkmI',
    appId: '1:848836773765:web:661c02d5b60d47602da6ec',
    messagingSenderId: '848836773765',
    projectId: 'usq1-7119d',
    authDomain: 'usq1-7119d.firebaseapp.com',
    storageBucket: 'usq1-7119d.firebasestorage.app',
    measurementId: 'G-XHRCBZVQKJ',
  );
}
